import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import AppNavbar from "@/components/layout/app-navbar";
import { Montserrat } from 'next/font/google';
import AppFooter from "@/components/layout/app-footer";
import SmoothScroller from "@/components/layout/smooth-scroller";

export const metadata: Metadata = {
  title: "GeoUI Studio - Web, App & UI/UX Development is Ratlam",
  description: "Generated by create next app",
};

const clashDisplay = localFont({
  src: [
    { path: '../public/fonts/ClashDisplay-Regular.woff2', weight: '400', style: 'normal' },
    { path: '../public/fonts/ClashDisplay-Medium.woff2', weight: '500', style: 'normal' },
    { path: '../public/fonts/ClashDisplay-Semibold.woff2', weight: '600', style: 'normal' },
    { path: '../public/fonts/ClashDisplay-Bold.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--font-clash',
  display: 'swap',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-montserrat',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full ${clashDisplay.variable} ${montserrat.variable} antialiased`}>
      <body className="min-h-full flex flex-col">
        <SmoothScroller>
          <AppNavbar />
          <main className="flex-1 w-full">{children}</main>
          <AppFooter />
        </SmoothScroller>
      </body>
    </html>
  );
}
